export const sortedTestData = [
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "shares": 10,
        "cost_basis": 120.50,
        "total_cost": 1205.00,
        "unit_price": 138.57,
        "current_value": 1385.70,
        "todays_gain_loss": 15.57,
        "todays_gain_loss_pct": 12.65,
        "gain_loss": 180.70,
        "gain_loss_pct": 15.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "TSLA",
        "name": "Tesla, Inc.",
        "shares": 5,
        "cost_basis": 210.00,
        "total_cost": 1050.00,
        "unit_price": 229.95,
        "current_value": 1149.75,
        "todays_gain_loss": 19.95,
        "todays_gain_loss_pct": 9.50,
        "gain_loss": 99.75,
        "gain_loss_pct": 9.50,
        "market_state": "REGULAR"
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices",
        "shares": 15,
        "cost_basis": 150.00,
        "total_cost": 2250.00,
        "unit_price": 162.30,
        "current_value": 2434.50,
        "todays_gain_loss": 12.30,
        "todays_gain_loss_pct": 8.20,
        "gain_loss": 184.50,
        "gain_loss_pct": 8.20,
        "market_state": "REGULAR"
    },
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "shares": 8,
        "cost_basis": 185.00,
        "total_cost": 1480.00,
        "unit_price": 189.62,
        "current_value": 1516.96,
        "todays_gain_loss": 3.42,
        "todays_gain_loss_pct": 1.84,
        "gain_loss": 36.96,
        "gain_loss_pct": 2.50,
        "market_state": "REGULAR"
    },
    {
        "symbol": "MMM",
        "name": "3M Company",
        "shares": 1,
        "cost_basis": 160.60,
        "total_cost": 160.60,
        "unit_price": 156.57,
        "current_value": 156.57,
        "todays_gain_loss": 1.87,
        "todays_gain_loss_pct": 1.21,
        "gain_loss": -4.03,
        "gain_loss_pct": -2.51,
        "market_state": "REGULAR"
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft Corp.",
        "shares": 4,
        "cost_basis": 420.00,
        "total_cost": 1680.00,
        "unit_price": 418.50,
        "current_value": 1674.00,
        "todays_gain_loss": -2.10,
        "todays_gain_loss_pct": -0.50,
        "gain_loss": -6.00,
        "gain_loss_pct": -0.36,
        "market_state": "REGULAR"
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet Inc.",
        "shares": 6,
        "cost_basis": 175.00,
        "total_cost": 1050.00,
        "unit_price": 171.15,
        "current_value": 1026.90,
        "todays_gain_loss": -3.15,
        "todays_gain_loss_pct": -1.81,
        "gain_loss": -23.10,
        "gain_loss_pct": -2.20,
        "market_state": "REGULAR"
    },
    {
        "symbol": "NKE",
        "name": "NIKE, Inc.",
        "shares": 12,
        "cost_basis": 95.00,
        "total_cost": 1140.00,
        "unit_price": 86.45,
        "current_value": 1037.40,
        "todays_gain_loss": -8.55,
        "todays_gain_loss_pct": -9.00,
        "gain_loss": -102.60,
        "gain_loss_pct": -9.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "INTC",
        "name": "Intel Corporation",
        "shares": 20,
        "cost_basis": 35.00,
        "total_cost": 700.00,
        "unit_price": 31.15,
        "current_value": 623.00,
        "todays_gain_loss": -3.85,
        "todays_gain_loss_pct": -11.00,
        "gain_loss": -77.00,
        "gain_loss_pct": -11.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "GME",
        "name": "GameStop Corp.",
        "shares": 50,
        "cost_basis": 28.00,
        "total_cost": 1400.00,
        "unit_price": 22.40,
        "current_value": 1120.00,
        "todays_gain_loss": -5.60,
        "todays_gain_loss_pct": -20.00,
        "gain_loss": -280.00,
        "gain_loss_pct": -20.00,
        "market_state": "REGULAR"
    }
];

export const unsortedTestData = [
    {
        "symbol": "GOOGL",
        "name": "Alphabet Inc.",
        "shares": 6,
        "cost_basis": 175.00,
        "total_cost": 1050.00,
        "unit_price": 171.15,
        "current_value": 1026.90,
        "todays_gain_loss": -3.15,
        "todays_gain_loss_pct": -1.81,
        "gain_loss": -23.10,
        "gain_loss_pct": -2.20,
        "market_state": "REGULAR"
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "shares": 10,
        "cost_basis": 120.50,
        "total_cost": 1205.00,
        "unit_price": 138.57,
        "current_value": 1385.70,
        "todays_gain_loss": 15.57,
        "todays_gain_loss_pct": 12.65,
        "gain_loss": 180.70,
        "gain_loss_pct": 15.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "INTC",
        "name": "Intel Corporation",
        "shares": 20,
        "cost_basis": 35.00,
        "total_cost": 700.00,
        "unit_price": 31.15,
        "current_value": 623.00,
        "todays_gain_loss": -3.85,
        "todays_gain_loss_pct": -11.00,
        "gain_loss": -77.00,
        "gain_loss_pct": -11.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "shares": 8,
        "cost_basis": 185.00,
        "total_cost": 1480.00,
        "unit_price": 189.62,
        "current_value": 1516.96,
        "todays_gain_loss": 3.42,
        "todays_gain_loss_pct": 1.84,
        "gain_loss": 36.96,
        "gain_loss_pct": 2.50,
        "market_state": "REGULAR"
    },
    {
        "symbol": "GME",
        "name": "GameStop Corp.",
        "shares": 50,
        "cost_basis": 28.00,
        "total_cost": 1400.00,
        "unit_price": 22.40,
        "current_value": 1120.00,
        "todays_gain_loss": -5.60,
        "todays_gain_loss_pct": -20.00,
        "gain_loss": -280.00,
        "gain_loss_pct": -20.00,
        "market_state": "REGULAR"
    },
    {
        "symbol": "TSLA",
        "name": "Tesla, Inc.",
        "shares": 5,
        "cost_basis": 210.00,
        "total_cost": 1050.00,
        "unit_price": 229.95,
        "current_value": 1149.75,
        "todays_gain_loss": 19.95,
        "todays_gain_loss_pct": 9.50,
        "gain_loss": 99.75,
        "gain_loss_pct": 9.50,
        "market_state": "REGULAR"
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft Corp.",
        "shares": 4,
        "cost_basis": 420.00,
        "total_cost": 1680.00,
        "unit_price": 418.50,
        "current_value": 1674.00,
        "todays_gain_loss": -2.10,
        "todays_gain_loss_pct": -0.50,
        "gain_loss": -6.00,
        "gain_loss_pct": -0.36,
        "market_state": "REGULAR"
    },
    {
        "symbol": "MMM",
        "name": "3M Company",
        "shares": 1,
        "cost_basis": 160.60,
        "total_cost": 160.60,
        "unit_price": 156.57,
        "current_value": 156.57,
        "todays_gain_loss": 1.87,
        "todays_gain_loss_pct": 1.21,
        "gain_loss": -4.03,
        "gain_loss_pct": -2.51,
        "market_state": "REGULAR"
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices",
        "shares": 15,
        "cost_basis": 150.00,
        "total_cost": 2250.00,
        "unit_price": 162.30,
        "current_value": 2434.50,
        "todays_gain_loss": 12.30,
        "todays_gain_loss_pct": 8.20,
        "gain_loss": 184.50,
        "gain_loss_pct": 8.20,
        "market_state": "REGULAR"
    },
    {
        "symbol": "NKE",
        "name": "NIKE, Inc.",
        "shares": 12,
        "cost_basis": 95.00,
        "total_cost": 1140.00,
        "unit_price": 86.45,
        "current_value": 1037.40,
        "todays_gain_loss": -8.55,
        "todays_gain_loss_pct": -9.00,
        "gain_loss": -102.60,
        "gain_loss_pct": -9.00,
        "market_state": "REGULAR"
    }
];